#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# C:\Users\Armen\Documents\GitHub\MPC\mwc.pl -type make
#
#----------------------------------------------------------------------------


all: qSort

depend: qSort-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.qSort $(@)

.PHONY: qSort
qSort:
	@$(MAKE) -f Makefile.qSort all

.PHONY: qSort-depend
qSort-depend:
	@$(MAKE) -f Makefile.qSort depend

project_name_list:
	@echo qSort
